# -*- coding: utf-8 -*-
"""manipalacao_img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WM4ZJidwT5GiJHCs_nplRtgI3RUxiJC2
"""

from PIL import Image
import numpy as np

path = '/content/drive/Lena_Gray_512.jpg' #Imagem 400x400px
#path = '/content/drive/Lena_original_512.png' #Imagem 400x400px


img = Image.open(path)
#gray = img.convert('L') #Converte para Luminos (Padrão de cinza) função do Pil

#formas de conversão para cinza
# Média: (R+G+B)/3 (é preciso converter p float, ppois essa soma direto no vetor pode ultrapassar 255 e dar erro)
#brilho (max(R,G,B) +min(R,G,B))/2 Esse não passa os 255, pois pega o maximo que so pode ser 255
#Luminosidade 0.21R+0.71g + 0.07B - Pega uma porcentagem de cada cor
#type(img)
#img
#img.show() #No python é preciso exibir a imagem

img = np.array(img) #Aqui em converto a imagem no padrão numpy com os valores dos pixels
#img = Image.fromarray(img) #Aqui eu converto no numpy para a imagem de volta
#img.save('temp.png') #Aqui eu salvo as alterações no disco
#type(img)
#img[0:100, 0:100] = (0,255,0) #Estou altrando os pixels de linha 0 até a 100 e coluna da 0 até 100
#img
#print(img.shape) #Dimensões da Imagem

#img[0,0] #Linha 0, coluna 0, os três canais RGB ou apenas o canal se for cinza
w, h = img.shape #Aqui estou pegando a largura e altura e jogando nas variávei para percorrer cada um dos pixels
#w, h ,nc = img.shape #Aqui estou pegando a largura e altura e jogando nas variávei para percorrer cada um dos pixels, bem como os canais se for RGB

# for x in range (w): #Pecorre cada uma das linhas (ex. 320x320, o for percorre 320)
#   for y in range (h): #Percorre as loculas de cada linha
#     print(img[x,y])

# for x in range (w): #Pecorre cada uma das linhas (ex. 320x320, o for percorre 320)
#   for y in range (h): #Percorre as loculas de cada linha
#     for z in range(nc): #Aqui ele percorre o canal
#       print(img[x,y,z]) #Imprime o pixel de cada dimensão

img = np.zeros((512,512)) #criou uma matriz 512x512 com zeros

img

img

img = np.zeros((512,512), dtype = np.uint8) #O uint8 (inteiro sem sinal de 8 bits) - se não adicionar da erro
#Quando eu for trabalhar com média por exemplo, tenho que converter entre float e int
#Converte para float, realiza a operação e retorna p int
# img[0,0] = 12
# soma = img[0,0] * img[0,0]
# print (soma)


#img_pil = Image.fromarray(img)
#img_pil.save('temp.jpg')